# Project details
[project_details]
project_id = dissertation-etl-496011
project_name = Dissertation-ETL

# Cluster details
[cluster_details]
cluster_name = cluster1
location = europe-southwest1

# Scripts locations
[scripts]
generate_extract = gs://europe-southwest1-datapipel-cfc3807e-bucket/scripts/pyspark_extract.py
transform = gs://europe-southwest1-datapipel-cfc3807e-bucket/scripts/pyspark_transform.py
model_creation = gs://europe-southwest1-datapipel-cfc3807e-bucket/scripts/pyspark_model_creation.py
load = gs://europe-southwest1-datapipel-cfc3807e-bucket/scripts/pyspark_load.py
db_connector = gs://europe-southwest1-datapipel-cfc3807e-bucket/scripts/DBConnector.py
logger = gs://europe-southwest1-datapipel-cfc3807e-bucket/scripts/Logger.py

# Files locations inside the bucket 
[buckets]
bronze = gs://dataops-assets/data/bronze
silver = gs://dataops-assets/data/silver
gold = gs://dataops-assets/data/gold
astheno = gs://dataops-assets/data/gold/asthenozoospermia
hypo = gs://dataops-assets/data/gold/hypospermia
necro = gs://dataops-assets/data/gold/necrospermia
oligo = gs://dataops-assets/data/gold/oligozoospermia
tera = gs://dataops-assets/data/gold/teratozoospermia
model = gs://dataops-assets/model/current_best_model

# Mongodb and PostgreSQL connection details
[database]
uri = mongodb://SemenDB_frightenor:e15d73a7bd41a29083d4aca92da0e2780957a258@3gvi9w.h.filess.io:27018/SemenDB_frightenor

[database_log]
uri = postgresql://PipelineLogs_nextmagnet:23b9adfc0ada24a03f328ee822a6f8d754ef210d@lwlt0n.h.filess.io:5434/PipelineLogs_nextmagnet

